config/routes.rb
YodleeResearch::Application.routes.draw do

  root 'yodlee_research#index'

  post 'yodlee_research/authenticate_cobrand' => 'yodlee_research#authenticate_cobrand'
  post 'yodlee_research/login_consumer' => 'yodlee_research#login_consumer'
  post 'yodlee_research/search_sites' => 'yodlee_research#search_sites'
  post 'yodlee_research/get_site_login_form' => 'yodlee_research#get_site_login_form'
  post 'yodlee_research/add_site_account' => 'yodlee_research#add_site_account'
  post 'yodlee_research/get_user_accounts' => 'yodlee_research#get_user_accounts'
  post 'yodlee_research/update_site_account_credentials' => 'yodlee_research#update_site_account_credentials'
  post 'yodlee_research/get_site_info' => 'yodlee_research#get_site_info'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/yodlee_research_controller.rb
require 'net/http'
require 'uri'

class YodleeResearchController < ApplicationController
  def index
  end

  def authenticate_cobrand
    params = {
      "cobrandLogin" => cobrand_username,
      "cobrandPassword" => cobrand_password
    }
    @result = JSON.parse(http_request(cobrand_login_url, params).body)
    respond_to do |format|
      format.js {}
    end
  end

  def login_consumer
    token = params["session_token"]

    login_params = {
      "cobSessionToken" => token,
      "login" => user_username,
      "password" => user_password
    }

    @result = JSON.parse(http_request(user_login_url, login_params).body)
    respond_to do |format|
      format.js {}
    end
  end

  def get_user_accounts
    session_token = params["session_token_5"]
    user_token = params["user_session_token_3"]

    account_params = {
      "cobSessionToken" => session_token,
      "userSessionToken" => user_token
    }

    @result = JSON.parse(http_request(get_user_accounts_url, account_params).body).collect { |x| x["siteInfo"]["defaultDisplayName"] }
    respond_to do |format|
      format.js {}
    end
  end

  def search_sites
    session_token = params["session_token_2"]
    user_token = params["user_session_token"]
    search = params["site_search_field"]

    search_params = {
      "cobSessionToken" => session_token,
      "userSessionToken" => user_token,
      "siteSearchString" => search
    }

    result_list = JSON.parse(http_request(search_site_url, search_params).body).collect { |x| "#{x["defaultDisplayName"]} | #{x["siteId"]}" }

    @result = []

    result_list.each do |r|
      @result << "<div>#{r}</div>"
    end

    respond_to do |format|
      format.js {}
    end
  end

  def get_site_info
    session_token = params["session_token_6"]
    site_id = params["site_id_3"]

    search_params = {
      "cobSessionToken" => session_token,
      "siteFilter.reqSpecifier" => 128,
      "siteFilter.siteId" => site_id
    }

    image_bytes = JSON.parse(http_request(get_site_info_url, search_params).body)["defaultSiteLogo"]["bytes"]
    image_string = image_bytes.pack('c*')
    base64_image = [image_string].pack('m0')

    @result = "<img alt='' src='data:image/jpeg;base64,#{base64_image}'/>"

    respond_to do |format|
      format.js {}
    end
  end

  def get_site_login_form

    session_token = params["session_token_3"]
    site_id = params["site_id"]

    login_form_params = {
      "cobSessionToken" => session_token,
      "siteId" => site_id
    }

    @result = JSON.parse(http_request(site_login_form_url, login_form_params).body)
    puts @result
    respond_to do |format|
      format.js {}
    end
  end

  def add_site_account
    session_token = params["session_token_4"]
    user_token = params["user_session_token_2"]
    site_id = params["site_id_2"]
    username = params["LOGIN1"]
    password = params["PASSWORD1"]

    add_site_params = {
      "cobSessionToken" => session_token,
      "userSessionToken" => user_token,
      "siteId" => site_id,
      "credentialFields.enclosedType" => "com.yodlee.common.FieldInfoSingle",
      "credentialFields[0].displayName" => "Username",
      "credentialFields[0].fieldType.typeName" => "TEXT",
      "credentialFields[0].name" => "LOGIN1",
      "credentialFields[0].value" => username,
      "credentialFields[0].valueIdentifier" => "LOGIN1",

      "credentialFields[1].displayName" => "Password",
      "credentialFields[1].fieldType.typeName" => "IF_PASSWORD",
      "credentialFields[1].name" => "PASSWORD1",
      "credentialFields[1].value" => password,
      "credentialFields[1].valueIdentifier" => "PASSWORD1"
    }

    @result = JSON.parse(http_request(add_site_url, add_site_params).body)

    respond_to do |format|
      format.js {}
    end
  end

  def update_site_account_credentials
    session_token = params["session_token_4"]
    user_token = params["user_session_token_2"]
    site_id = params["site_id_2"]
    username = params["LOGIN1"]
    password = params["PASSWORD1"]

    add_site_params = {
      "cobSessionToken" => session_token,
      "userSessionToken" => user_token,
      "siteId" => site_id,
      "credentialFields.enclosedType" => "com.yodlee.common.FieldInfoSingle",
      "credentialFields[0].displayName" => "Username",
      "credentialFields[0].fieldType.typeName" => "TEXT",
      "credentialFields[0].name" => "LOGIN1",
      "credentialFields[0].value" => username,
      "credentialFields[0].valueIdentifier" => "LOGIN1",

      "credentialFields[1].displayName" => "Password",
      "credentialFields[1].fieldType.typeName" => "IF_PASSWORD",
      "credentialFields[1].name" => "PASSWORD1",
      "credentialFields[1].value" => password,
      "credentialFields[1].valueIdentifier" => "PASSWORD1"
    }

    @result = JSON.parse(http_request(update_site_account_credentials_url, add_site_params).body)

    respond_to do |format|
      format.js {}
    end
  end

  private

  def http_request(url, params)
    http = Net::HTTP.new(url.host, url.port)
    request = Net::HTTP::Post.new(url.request_uri)
    request.form_data = params
    http.use_ssl = true  
    http.request(request)
  end

  def user_username
    "sbMemsbCobJMatthewman1"
  end

  def user_password
    "sbMemsbCobJMatthewman1#123"
  end

  def cobrand_username
    "sbCobsbCobJMatthewman"
  end

  def cobrand_password
    #"2c5c5015-0861-43f5-b81f-7b69d943051A"
    "0db1a34f-7963-4550-b69b-2aeda113f9c4"
  end

  def rest_url
    "https://rest.developer.yodlee.com/services/srest/restserver/v1.0/"
  end

  def cobrand_login_url
    URI.parse("#{rest_url}authenticate/coblogin")
  end

  def user_login_url
    URI.parse("#{rest_url}authenticate/login")
  end

  def search_site_url
    URI.parse("#{rest_url}jsonsdk/SiteTraversal/searchSite")
  end

  def get_site_info_url
    URI.parse("#{rest_url}jsonsdk/SiteTraversal/getSiteInfo")
  end

  def site_login_form_url 
    URI.parse("#{rest_url}jsonsdk/SiteAccountManagement/getSiteLoginForm")
  end

  def add_site_url
    URI.parse("#{rest_url}jsonsdk/SiteAccountManagement/addSiteAccount1")
  end

  def update_site_account_credentials_url
    URI.parse("#{rest_url}jsonsdk/SiteAccountManagement/updateSiteAccountCredentials")
  end

  def get_user_accounts_url
    URI.parse("#{rest_url}jsonsdk/SiteAccountManagement/getSiteAccounts")
  end

  def get_site_account_mfa_questions_and_answers_url
    URI.parse("#{rest_url}jsonsdk/SiteAccountManagement/getSiteAccountMfaQuestionsAndAnswers")
  end

  def get_mfa_response_for_site_url
    URI.parse("#{rest_url}jsonsdk/SiteAccountManagement/getMFAResponseForSite")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/yodlee_research_helper.rb
module YodleeResearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YodleeResearch</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/yodlee_research/add_site_account.js.erb
$('#add_site_account_response').html('<%= @result %>');

app/views/yodlee_research/authenticate_cobrand.js.erb
$('#authenticate_cobrand_result').html("<%= @result %>");
$('#session_token').attr('value', "<%= @result["cobrandConversationCredentials"]["sessionToken"] %>");
$('#session_token_2').attr('value', "<%= @result["cobrandConversationCredentials"]["sessionToken"] %>");
$('#session_token_3').attr('value', "<%= @result["cobrandConversationCredentials"]["sessionToken"] %>");
$('#session_token_4').attr('value', "<%= @result["cobrandConversationCredentials"]["sessionToken"] %>");
$('#session_token_5').attr('value', "<%= @result["cobrandConversationCredentials"]["sessionToken"] %>");
$('#session_token_6').attr('value', "<%= @result["cobrandConversationCredentials"]["sessionToken"] %>");

app/views/yodlee_research/get_site_info.js.erb
$('#get_site_info_response').html("<%= @result.html_safe %>");

app/views/yodlee_research/get_site_login_form.js.erb
$('#login_extras').html('');
$('#login_extras2').html('');

<% @result["componentList"].each do |field| %>
  $('#login_extras').append('<%= label_tag field["displayName"] %>');
  $('#login_extras').append('<%= text_field_tag field["valueIdentifier"] %>');
  $('#login_extras').append('<br />');
<% end %>

<% @result["componentList"].each do |field| %>
  $('#login_extras2').append('<%= label_tag field["displayName"] %>');
  $('#login_extras2').append('<%= text_field_tag field["valueIdentifier"] %>');
  $('#login_extras2').append('<br />');
<% end %>

app/views/yodlee_research/get_user_accounts.js.erb
$('#user_accounts_response').html('<%= @result %>')

app/views/yodlee_research/index.html.erb
<h1>Authenticate Cobrand</h1>

<%= form_tag(yodlee_research_authenticate_cobrand_path, method: :post, remote: true) do %>
  <%= submit_tag("Authenticate Cobrand") %>
<% end %>

<h3>Response</h3>
<div id="authenticate_cobrand_result"></div>

<h1>Login Consumer</h1>

<%= form_tag(yodlee_research_login_consumer_path, method: :post, remote: true) do %>
  <%= label_tag "Session token" %>
  <%= text_field_tag "session_token" %><br/>
  <%= submit_tag("Login Consumer") %>
<% end %>

<h3>Response</h3>
<div id="login_consumer_result"></div>

<h1>Get sites for user</h1>

<%= form_tag(yodlee_research_get_user_accounts_path, method: :post, remote: true) do %>
  <%= label_tag "Session token" %>
  <%= text_field_tag "session_token_5" %><br/>

  <%= label_tag "User session token" %>
  <%= text_field_tag "user_session_token_3" %><br/>
  <%= submit_tag("Get user accounts") %>
<% end %>

<h3>Response</h3>

<div id="user_accounts_response"></div>

<h1>Find Sites</h1>

<%= form_tag(yodlee_research_search_sites_path, method: :post, remote: true) do %>
  <%= label_tag "Session token" %>
  <%= text_field_tag "session_token_2" %><br/>

  <%= label_tag "User session token" %>
  <%= text_field_tag "user_session_token" %><br/>

  <%= label_tag "Search" %>
  <%= text_field_tag "site_search_field" %><br/>

  <%= submit_tag("Search sites") %>
<% end %>

<h3>Response</h3>
<div id="search_sites_result"></div>

<h1>Get site login form</h1>

<%= form_tag(yodlee_research_get_site_login_form_path, method: :post, remote: true) do %>
  <%= label_tag "Session token" %>
  <%= text_field_tag "session_token_3" %><br/>

  <%= label_tag "Site ID" %>
  <%= text_field_tag "site_id" %><br/>

  <%= submit_tag("Get site login form") %>

<% end %>


<h1>Site Login Form</h1>

<div id="site_login_form">
  <%= form_tag(yodlee_research_add_site_account_path, method: :post, remote: true) do %>
  <%= label_tag "Session token" %>
  <%= text_field_tag "session_token_4" %><br/>

  <%= label_tag "User session token" %>
  <%= text_field_tag "user_session_token_2" %><br/>

  <%= label_tag "Site ID" %>
  <%= text_field_tag "site_id_2" %><br/>

    <div id="login_extras">
      Waiting for Site ID.
    </div>
    <%= submit_tag "Add Site Account" %>
  <% end %>

<h3>Response</h3>
<div id="add_site_account_response"></div>

<h1>Update Credentials Form</h1>

<div id="update_credentials_form">
  <%= form_tag(yodlee_research_update_site_account_credentials_path, method: :post, remote: true) do %>
  <%= label_tag "Session token" %>
  <%= text_field_tag "session_token_4" %><br/>

  <%= label_tag "User session token" %>
  <%= text_field_tag "user_session_token_2" %><br/>

  <%= label_tag "Site ID" %>
  <%= text_field_tag "site_id_2" %><br/>

    <div id="login_extras2">
      Waiting for Site ID.
    </div>
    <%= submit_tag "Update Site Account Credentials" %>
  <% end %>

<h3>Response</h3>
<div id="update_site_account_credentials_response"></div>
</div>

<h1>Get Site Info Form</h1>

<div id="get_site_info_form">
  <%= form_tag(yodlee_research_get_site_info_path, method: :post, remote: true) do %>
  <%= label_tag "Session token" %>
  <%= text_field_tag "session_token_6" %><br/>

  <%= label_tag "Site ID" %>
  <%= text_field_tag "site_id_3" %><br/>

  <div id="login_extras3">
    Waiting for Site ID.
  </div>
  <%= submit_tag "Get Site Info" %>
<% end %>

<h3>Response</h3>
<div id="get_site_info_response"></div>
</div>

app/views/yodlee_research/login_consumer.js.erb
$('#login_consumer_result').html('<%= @result %>');
$('#user_session_token').attr('value', '<%= @result["userContext"]["conversationCredentials"]["sessionToken"] %>'); 
$('#user_session_token_2').attr('value', '<%= @result["userContext"]["conversationCredentials"]["sessionToken"] %>'); 
$('#user_session_token_3').attr('value', '<%= @result["userContext"]["conversationCredentials"]["sessionToken"] %>');

app/views/yodlee_research/search_sites.js.erb
$('#search_sites_result').html("<%= @result.join.html_safe %>");

app/views/yodlee_research/update_site_account_credentials.js.erb
$('#update_site_account_credentials_response').html('<%= @result %>');